# Generated by Django 4.2.20 on 2026-06-09 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('laundries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del cliente')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo electrónico')),
                ('phone_number', models.CharField(blank=True, max_length=10, null=True, verbose_name='Número de teléfono')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('rfc', models.CharField(blank=True, max_length=13, null=True, verbose_name='RFC')),
                ('laundry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='laundries.laundry', verbose_name='Lavandería')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['name'],
            },
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(condition=models.Q(('rfc__isnull', False)), fields=('laundry', 'rfc'), name='unique_client_rfc_per_laundry'),
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(condition=models.Q(('email__isnull', False)), fields=('laundry', 'email'), name='unique_client_email_per_laundry'),
        ),
    ]
