# Generated by Django 4.2.20 on 2026-06-09 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='client',
            name='unique_client_email_per_laundry',
        ),
    ]
