# Generated by Django 4.2.20 on 2026-06-09 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('laundries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la categoría')),
                ('laundry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='laundries.laundry', verbose_name='Lavandería')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(editable=False, help_text='Generado automáticamente: prefijo de la lavandería + 15 dígitos.', max_length=20, verbose_name='Folio')),
                ('folio_number', models.PositiveBigIntegerField(editable=False, null=True, verbose_name='Consecutivo del folio')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del producto')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='product.category', verbose_name='Categoría')),
                ('laundry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='laundries.laundry', verbose_name='Lavandería')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['folio'],
            },
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('laundry', 'name'), name='unique_product_name_per_laundry'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('laundry', 'folio'), name='unique_product_folio_per_laundry'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('laundry', 'name'), name='unique_category_name_per_laundry'),
        ),
    ]
