# Generated by Django 4.2.20 on 2026-06-09 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.RemoveConstraint(
            model_name='product',
            name='unique_product_folio_per_laundry',
        ),
        migrations.RemoveField(
            model_name='product',
            name='folio',
        ),
        migrations.RemoveField(
            model_name='product',
            name='folio_number',
        ),
    ]
