# Generated by Django 4.2.20 on 2026-06-09 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
        ('laundries', '0002_laundrystaff'),
        ('product', '0002_alter_product_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(editable=False, help_text='Se genera al guardar: prefijo de la lavandería + 15 dígitos.', max_length=20, verbose_name='Folio de venta')),
                ('folio_number', models.PositiveBigIntegerField(editable=False, null=True, verbose_name='Consecutivo del folio')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de venta')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='client.client', verbose_name='Cliente')),
                ('laundry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='laundries.laundry', verbose_name='Lavandería')),
            ],
            options={
                'verbose_name': 'Ticket de venta',
                'verbose_name_plural': 'Tickets de venta',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Precio del producto al momento de la venta; no cambia aunque el catálogo cambie.', max_digits=10, verbose_name='Precio unitario (congelado)')),
                ('subtotal', models.DecimalField(decimal_places=2, editable=False, max_digits=12, verbose_name='Subtotal')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ticket_details', to='product.product', verbose_name='Producto')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='service.ticket', verbose_name='Ticket')),
            ],
            options={
                'verbose_name': 'Detalle de venta',
                'verbose_name_plural': 'Detalles de venta',
            },
        ),
        migrations.AddConstraint(
            model_name='ticketdetail',
            constraint=models.UniqueConstraint(fields=('ticket', 'product'), name='unique_product_per_ticket'),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(fields=('laundry', 'folio'), name='unique_ticket_folio_per_laundry'),
        ),
    ]
