# Generated by Django 4.2.30 on 2026-06-11 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='delivery_date_time',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora estimada de entrega al cliente; opcional.', null=True, verbose_name='Fecha y hora de entrega'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='paid',
            field=models.BooleanField(default=False, editable=False, verbose_name='¿Pagado?'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='partial_payment',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Anticipo que deja el cliente; opcional.', max_digits=12, verbose_name='Pago parcial'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='remaining_balance',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, help_text='Se calcula solo: total menos el pago parcial. Nunca es negativo.', max_digits=12, verbose_name='Saldo restante'),
        ),
    ]
