# Generated by Django 4.2.20 on 2026-06-09 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laundry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nombre de la lavandería')),
                ('prefix', models.CharField(blank=True, help_text='3 o 4 letras en mayúsculas. Si se deja vacío se deriva del nombre.', max_length=4, unique=True, verbose_name='Prefijo de folio')),
                ('folio_counter', models.PositiveBigIntegerField(default=0, editable=False, help_text='Secuencia interna de folios. Es monotónica: nunca se reutiliza.', verbose_name='Último número de folio asignado')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de alta')),
            ],
            options={
                'verbose_name': 'Lavandería',
                'verbose_name_plural': 'Lavanderías',
                'ordering': ['name'],
            },
        ),
    ]
