# Generated by Django 4.2.20 on 2026-06-09 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('laundries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaundryStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_tenant_admin', models.BooleanField(default=False, verbose_name='Administrador de la lavandería')),
                ('laundry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='laundries.laundry', verbose_name='Lavandería')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='laundry_membership', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Usuario de lavandería',
                'verbose_name_plural': 'Usuarios de lavandería',
            },
        ),
    ]
